import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const CheckoutForm = () => {
  const state = useSelector((state) => state);
  const { totalPrice, products, users } = state;
  const [finalPrice, setFinalPrice] = useState(totalPrice + 100);
  const [alert, setAlert] = useState("");
  const [voucher, setVoucher] = useState("");

  //form data
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [address, setAddress] = useState("");

  const dispatch = useDispatch();

  const addUserDetails = () => {
    dispatch({
      type: "ADD_USER_DETAILS",
      payload: {
        name,
        email,
        address,
      },
    });
  };

  const handleVoucher = () => {
    if (voucher === "Discount5") {
      setFinalPrice(totalPrice - (totalPrice * 5) / 100 + 100);
      setAlert("5% Discount Applied");
    } else if (voucher === "Discount10") {
      setFinalPrice(totalPrice - (totalPrice * 10) / 100 + 100);
      setAlert("10% Discount Applied");
    } else if (voucher === "Special300") {
      setFinalPrice(totalPrice - 300 + 100);
      setAlert("300 TK Discount Applied");
    }
  };
  return (
    <>
      <Head>
        <title>Checkout Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:flex gap-8 container mx-auto my-10">
        <div className="lg:w-1/2 flex flex-col gap-2 border p-8 shadow-xl rounded-lg">
          <p className="text-xl font-semibold">
            Delivery Informaion {users.name}
          </p>
          <input
            type="text"
            placeholder="Enter name"
            className="input input-bordered w-full block"
            onBlur={(e) => setName(e.target.value)}
            required
          />
          <input
            type="email"
            placeholder="Enter email"
            className="input input-bordered w-full block"
            onBlur={(e) => setEmail(e.target.value)}
            required
          />
          <textarea
            placeholder="Enter address"
            className="textarea textarea-bordered textarea-lg w-full block"
            onBlur={(e) => setAddress(e.target.value)}
            required
          />
        </div>

        <div className="lg:w-1/2 flex flex-col gap-2 mt-5 border p-8 shadow-xl rounded-lg">
          <p className="text-xl font-semibold">Order Summery</p>
          <div className="flex justify-between">
            <p className="font-semibold">Product</p>
            <p className="font-semibold">Price</p>
          </div>
          {products.map((p, i) => (
            <div key={i} className="flex justify-between">
              <p className="font-semibold">{p.name}</p>
              <p className="font-semibold">{p.price} BDT</p>
            </div>
          ))}
          <div className="flex justify-between">
            <p className="font-semibold">Total Price:</p>
            <p className="text-orange-600 font-semibold">{totalPrice} BDT</p>
          </div>
          <div className="flex justify-between">
            <p className="font-semibold">Delivery Charges:</p>
            <p className="text-orange-600 font-semibold">100 BDT</p>
          </div>
          {/* Add your voucher here */}
          <div className="relative">
            <input
              type="text"
              name="voucher"
              placeholder="Enter voucher"
              className="input input-bordered w-full pr-16"
              onBlur={(e) => setVoucher(e.target.value)}
            />
            <button
              onClick={handleVoucher}
              className="btn bg-orange-600 border-0 absolute top-0 right-0 rounded-l-none"
            >
              Apply
            </button>
          </div>
          <p className="font-semibold text-blue-500">{alert}</p>
          <div className="flex justify-between">
            <p className="font-semibold">Final Price:</p>
            <p className="text-orange-600 font-semibold">{finalPrice} BDT</p>
          </div>
          <div className="my-5">
            <p className="font-semibold text-center">Select Payment Option</p>
            <div className="flex justify-around mt-5">
              <div className="flex gap-2">
                <input type="radio" name="radio-4" className="radio" />
                <p>Cash On Delivery</p>
              </div>
              <div className="flex gap-2">
                <input type="radio" name="radio-4" className="radio" />
                <p>Online Payment</p>
              </div>
            </div>
          </div>
          <button
            onClick={addUserDetails}
            className="btn bg-orange-600 rounded-lg border-0"
          >
            Place Order
          </button>

          {/* The button to open modal */}
          <label htmlFor="my-modal" className="btn">
            Check Order
          </label>

          {/* Put this part before </body> tag */}
          <input type="checkbox" id="my-modal" className="modal-toggle" />
          <div className="modal">
            <div className="modal-box">
              <h3 className="font-bold text-lg">
                {users.map((u) => (
                  <p>{u.name}</p>
                ))}
              </h3>
              <div className="flex justify-between">
                <p className="font-semibold">Product</p>
                <p className="font-semibold">Price</p>
              </div>
              {products.map((p, i) => (
                <div key={i} className="flex justify-between">
                  <p className="font-semibold">{p.name}</p>
                  <p className="font-semibold">{p.price} BDT</p>
                </div>
              ))}
              <p className="text-orange-600 font-semibold">
                You have to pay {finalPrice} BDT
              </p>
              <div className="modal-action">
                <label htmlFor="my-modal" className="btn">
                  Ok
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default CheckoutForm;
